### ISSUE TITLE
ga ketemu

### ISSUE THREAD

**Issue by rfzio** [riochr17/POSTag-Chunker-ID#1]
Hello can you help me? I got this error message

ga ketemu
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from chunker import Chunker
  File "D:\College\R\Git\POSTag-Chunker-ID\chunker.py", line 20, in <module>
    class MarkPlaceholders(dict):
  File "D:\College\R\Git\POSTag-Chunker-ID\chunker.py", line 21, in MarkPlaceholders
    self.UNIQ='_UNIQUE_STRING_'
NameError: name 'self' is not defined

**Comment by riochr17** [comment]
python yang dipakai versi berapa?; *which version of python do you use?*

**Comment by riochr17** [comment]
https://github.com/riochr17/POSTag-Chunker-ID/blob/b52bfed006a77d872c17a3c4b3690399d4f67c9c/chunker.py#L20-L23

```python
self.UNIQ='_UNIQUE_STRING_'
```

ganti jadi; *change to*
```python
UNIQ='_UNIQUE_STRING_'
```

install dependensi `pycrfsuite`; *install dependency* `pycrfsuite`
```bash
pip install python-crfsuite
```

**Comment by rfzio** [comment]
solved! thanks.
